version: '3.8'

services:

  db:
    image: mysql:8
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: abi
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306" 
    volumes:
      - ./infra:/var/lib/mysql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node-app
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=mysql://root:rootpassword@db:3306/abi
    volumes:
      - .:/app
    depends_on:
      - db

volumes:
  postgres-data:
    driver: local